### ISSUE TITLE
实验三笔记 ACL简化

### ISSUE THREAD

**Issue by colinaaa** [HUSTERGS/Computer_Network#1]
在 实验三-综合部分中，有部分ACL配置可以简化

以第一个宿舍，dorm-1-in为例

- `access-list 101 deny ip 211.69.4.0 0.0.0.255 211.69.7.128 0.0.0.127`
- `access-list 101 deny ip 211.69.4.0 0.0.0.255 211.69.7.160 0.0.0.127`
- `access-list 101 deny ip 211.69.4.0 0.0.0.255 211.69.7.192 0.0.0.127`
- `access-list 101 deny ip 211.69.4.0 0.0.0.255 211.69.7.224 0.0.0.127`

中， `0.0.0.127` 为通配符，指ip地址中，为1的位可任意选取，为0的部分需和指定ip匹配。

因此以上三条可简化为

`access-list 101 deny ip 211.69.4.0 0.0.0.255 211.69.7.128 0.0.0.127`

这一条即可

其他规则类似

**Comment by HUSTERGS** [comment]
已在`笔记.md`中增加相关提醒。非常感谢

**Comment by colinaaa** [comment]
❤️
